---
- hosts: all
  become: yes
  tasks:
  - name: Install pip python3
    apt:
      name: python3-pip
      update_cache: yes

  - name: Install python3 docker package
    pip:
      name: ['docker', 'docker[tls]', 'docker-compose']